### ISSUE TITLE
Can you add Mysql support? I have bungeecord server!

### ISSUE THREAD

**Issue by zzvenuszz** [ebildude123/KillRankSystem#1]
I'm changing myserver to run bungeecord, i had old KRS database storaged in points.db and kills.db
I'd love mysql support so my database could sync accross servers.
A command to import database from sqlite to mysql too?
Thanks for reading, I really need this....

**Comment by weidizhang** [comment]
Sorry, not planning on adding any features at this time.

You are free to modify the source code with MySQL support yourself given that the license is followed: https://github.com/weidizhang/KillRankSystem/blob/master/LICENSE.md
